version: '3.8'

services:
  backend:
    image: chat_real_time:backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    # command: 'daphne -b 0.0.0.0 -p 8000 backend.asgi:application'
    command: 'python manage.py runserver 0.0.0.0:8000'
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app

  redis:
    image: chat_real_time:redis
    build:
      context: ./redis
      dockerfile: Dockerfile
    command: 'redis-server /usr/local/etc/redis/redis.conf'